import { index, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("games", "routes/games.tsx"),
  route("games/:slug", "routes/game-slug.tsx"),
  route("ranking", "routes/ranking.tsx"),
  route("profile", "routes/profile.tsx"),
  route("admin", "routes/admin.tsx"),
  route("admin/creators", "routes/adminCreators.tsx"),
  route("admin/accounts", "routes/adminAccounts.tsx"),
  route("admin/settings/security", "routes/adminSettingsSecurity.tsx"),
  route("discord", "routes/discordHub.tsx"),
  route("discord/setup", "routes/discordSetup.tsx"),
  route("discord/guide", "routes/discordGuide.tsx"),
  route("discord/link", "routes/discordLink.tsx"),
  route("discord/servers", "routes/discordServers.tsx"),
  route("discord/servers/:slug", "routes/discordServerSlug.tsx"),
  route("discord/servers/:slug/manage", "routes/discordServerManage.tsx"),
  route("wiki", "routes/wiki.tsx"),
  route("wiki/getting-started", "routes/wikiGettingStarted.tsx"),
  route("wiki/discord", "routes/wikiDiscord.tsx"),
  route("wiki/discord/install", "routes/wikiDiscordInstall.tsx"),
  route("wiki/discord/account-link", "routes/wikiDiscordAccountLink.tsx"),
  route("wiki/discord/server-registration", "routes/wikiDiscordServerRegistration.tsx"),
  route("wiki/discord/commands", "routes/wikiDiscordCommands.tsx"),
  route("wiki/discord/xp", "routes/wikiDiscordXp.tsx"),
  route("wiki/discord/troubleshooting", "routes/wikiDiscordTroubleshooting.tsx"),
  route("wiki/account", "routes/wikiAccount.tsx"),
  route("wiki/account/merge", "routes/wikiAccountMerge.tsx"),
  route("wiki/games", "routes/wikiGames.tsx"),
  route("wiki/games/ranking", "routes/wikiGamesRanking.tsx"),
  route("wiki/games/xp", "routes/wikiGamesXp.tsx"),
  route("wiki/creator", "routes/wikiCreator.tsx"),
  route("wiki/creator/verification", "routes/wikiCreatorVerification.tsx"),
  route("wiki/creator/featured", "routes/wikiCreatorFeatured.tsx"),
  route("terms", "routes/terms.tsx"),
  route("privacy", "routes/privacy.tsx"),
] satisfies RouteConfig;
