// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/games": {
    params: {};
  };
  "/games/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ranking": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/api/auth/callback/:provider": {
    params: {
      "provider": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/games" | "/games/:slug" | "/ranking" | "/profile" | "/api/auth/callback/:provider";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/games.tsx": {
    id: "routes/games";
    page: "/games";
  };
  "routes/game-slug.tsx": {
    id: "routes/game-slug";
    page: "/games/:slug";
  };
  "routes/ranking.tsx": {
    id: "routes/ranking";
    page: "/ranking";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/api.auth.callback.$provider.tsx": {
    id: "routes/api.auth.callback.$provider";
    page: "/api/auth/callback/:provider";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/games": typeof import("./app/routes/games.tsx");
  "routes/game-slug": typeof import("./app/routes/game-slug.tsx");
  "routes/ranking": typeof import("./app/routes/ranking.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/api.auth.callback.$provider": typeof import("./app/routes/api.auth.callback.$provider.tsx");
};