// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/games": {
    params: {};
  };
  "/games/:slug": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/games" | "/games/:slug";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/games.tsx": {
    id: "routes/games";
    page: "/games";
  };
  "routes/game-slug.tsx": {
    id: "routes/game-slug";
    page: "/games/:slug";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/games": typeof import("./app/routes/games.tsx");
  "routes/game-slug": typeof import("./app/routes/game-slug.tsx");
};